# -*- coding: utf-8 -*-
"""Emit the English content modules for printed 20-48 from `scan_reading/english/*.txt`.

Same reason as `generate_he_korbanot.py`: the text is long and typing it is how words go
wrong. `reverse` then checks every page against the reading.

**The two sides do not part their paragraphs in the same places**, and that is the one
thing this script has to get right, because parallel alignment joins on exact URN equality.
Three shapes occur:

- *The English parts where the Hebrew does not.* The Akedah is one paragraph in Hebrew and
  four in English. Both sides carry one `prayer:akedah`, so the join is at the division and
  the paragraphing inside it is each side's own.
- *The Hebrew parts where the English does not.* Printed 25 breaks `לְפִיכָךְ` at the
  `Reader` label and printed 26 runs straight on. The Hebrew's parting is what creates the
  URN, so the **English has to be parted at the same place** or the two sides join one URN
  against two. Those splits are declared in :data:`SPLIT`.
- *Neither parts.* Everything else.
"""
import pathlib
import textwrap

ST = pathlib.Path("/home/efeins/src/opensiddur-repos/sourcetexts/feat_birnbaum-birchot-hashachar/sources/birnbaum_siddur/scan_reading")
PAGES = {p: (ST / "english" / f"{p}.txt").read_text(encoding="utf-8").strip().split("\n\n")
         for p in range(20, 49, 2)}

#: Where the English runs on and the Hebrew parts. The value is the first words of the
#: second half; everything before it is the first. Each is the point at which the Hebrew
#: page sets a `Reader` label -- see `readings/25.md`.
SPLIT = {
    (26, 0): "Happy are we who, early and late,",
    (26, 3): "May our strength rise and be exalted",
}


def para(page, i, half=None):
    text = PAGES[page][i]
    if (page, i) in SPLIT:
        at = text.index(SPLIT[(page, i)])
        text = text[:at].strip() if half == 0 else text[at:].strip()
    elif half is not None:
        raise SystemExit(f"({page}, {i}) has no declared split")
    return " ".join(text.split())


def literal(text, first_prefix="", indent=9):
    pad = " " * indent
    wrapped = textwrap.wrap(text, width=74, break_on_hyphens=False)
    out = []
    for n, line in enumerate(wrapped):
        tail = " " if n < len(wrapped) - 1 else ""
        body = line.replace('\\', '\\\\').replace('"', '\\"')
        if n == 0 and first_prefix:
            out.append(f'{pad}f"{first_prefix}{body}{tail}"')
        else:
            out.append(f'{pad}"{body}{tail}"')
    return "\n".join(out)


HEAD = '''# -*- coding: utf-8 -*-
"""%s

Generated by `specs/birnbaum_scan/generate_english_modules.py` from the English readings,
and checked page by page with `reverse`.
"""
import functools

from .common import PRAYER, POEM
from . import common

pb = functools.partial(common.pb, sigil=common.SIGIL_BIRCHOT)

U = PRAYER
P = POEM

PRAYERS = []


def prayer(name, title, slug, first, last, body, *, base=None):
    PRAYERS.append(dict(name=name, title=title, urn=(base or U) + slug,
                        first=first, last=last, body=body))


def d(urn, *paras, indent=8):
    pad = " " * indent
    inner = "\\n".join(f"{pad}  <tei:p>{p}</tei:p>" for p in paras)
    return f'{pad}<tei:div corresp="{urn}">\\n{inner}\\n{pad}</tei:div>'


def verses(urn, ls, *, indent=8):
    pad = " " * indent
    inner = "\\n".join(f"{pad}    <tei:l>{line}</tei:l>" for line in ls)
    return ('%%s<tei:div corresp="%%s">\\n%%s  <tei:lg>\\n%%s\\n%%s  </tei:lg>\\n%%s</tei:div>'
            %% (pad, urn, pad, inner, pad, pad))

'''


def block(name, title, slug, first, last, paragraphs, base=None, comment=None):
    """`paragraphs` is a list of (page, index, half) or (page, index)."""
    out = []
    if comment:
        out.append(comment)
    body = []
    page_seen = first
    for item in paragraphs:
        page, index = item[0], item[1]
        half = item[2] if len(item) > 2 else None
        brk = "{pb(%d)}" % page if page != page_seen else ""
        page_seen = page
        body.append(literal(para(page, index, half), first_prefix=brk))
    joined = ",\n".join(body)
    extra = ", base=P" if base else ""
    out.append(f'prayer("{name}", "{title}", "{slug}", {first}, {last},\n'
               f'       d({"P" if base else "U"} + "{slug}",\n{joined}){extra})\n')
    return "\n".join(out)


def verse_block(name, title, slug, first, last, items, base=None, comment=None):
    out = []
    if comment:
        out.append(comment)
    page_seen = first
    ls = []
    for page, index in items:
        brk = "{pb(%d)}" % page if page != page_seen else ""
        page_seen = page
        text = para(page, index).replace('"', '\\"')
        ls.append(f'           f"{brk}{text}",' if brk else f'           "{text}",')
    extra = ", base=P" if base else ""
    out.append(f'prayer("{name}", "{title}", "{slug}", {first}, {last},\n'
               f'       verses({"P" if base else "U"} + "{slug}", [\n'
               + "\n".join(ls) + f"\n       ]){extra})\n")
    return "\n".join(out)


AKEDAH_DOC = """The English of the Akedah and the setting for the Shema, printed pages 20 to 26.

**The Akedah is one paragraph in Hebrew and four in English.** Both sides carry one
`prayer:akedah`, so the two columns join at the division and each parts its own prose.

**`לְפִיכָךְ` and `אַתָּה הוּא` are parted in Hebrew and not in English.** Printed 25 sets a
`Reader` label inside each, which makes the second half its own text with its own URN;
printed 26 runs straight on. The English is parted at the same two points so that the two
sides join URN for URN -- a passage that must start level with its translation needs a URN
of its own, and here the Hebrew page is what creates it.

The Shema verse and Barukh Shem are realised by the children's unit and transcluded."""

KORBANOT_DOC = """The English of the korbanot, printed pages 28 to 42.

The citations are centred italic lines on this side as they are on the Hebrew side, and
they are `tei:head` on the unit rather than text of the prayers -- the same fact in each
language's own convention, `Exodus 30:17-21` against `שמות ל, יז-כא`. Ranges take an en
dash in both.

**Pittum ha-Ketoreth is one paragraph in Hebrew and three in English**, and Eizehu
Mekoman's mishnayoth are numbered `1.` here and `א.` there. Both are each side's own and
neither affects the join, which is at the division."""

ISHMAEL_DOC = """The English of Rabbi Ishmael's rules and Kaddish d'Rabbanan, printed 42 to 48.

**This side carries a heading the Hebrew side does not** -- `TALMUDIC EXPOSITION OF THE
SCRIPTURES`, centred in small capitals over printed 42, where printed 41 goes straight from
the tail of Zevaḥim to its citation. It is in the unit body, not here.

The rules are numbered `1.` here and `א)` there; the closing rubric names **page 300** here
and page 299 there, each side pointing at its own half of the target opening."""

# ---------------------------------------------------------------- en_akedah
A = []
A.append(block("akedah", "The binding of Isaac", "akedah", 20, 22,
               [(20, 3), (20, 4), (22, 0), (22, 1), (22, 2)],
               comment="#: Four paragraphs here against one in Hebrew; the page turn falls\n"
                       "#: inside the second, at `we will worship and | come back to you.`"))
A.append(block("akedah_ribbono", "Master of the world", "akedah/ribbono_shel_olam", 22, 24,
               [(22, 3), (24, 0)]))
A.append(block("leolam_yehe_adam", "Man should ever be God-fearing", "leolam_yehe_adam",
               24, 24, [(24, 1)]))
A.append(block("ribbon_kol_haolamim", "Master of all worlds", "ribbon_kol_haolamim",
               24, 24, [(24, 2)]))
A.append(block("aval_anachnu", "However, we are thy people", "aval_anachnu", 24, 24,
               [(24, 3)]))
A.append(block("lefikhakh", "Therefore it is our duty", "lefikhakh", 26, 26,
               [(26, 0, 0)],
               comment="#: Parted from what follows because printed 25 parts it: the\n"
                       "#: `Reader` label falls between them on the Hebrew page."))
A.append(block("ashrenu", "Happy are we who, early and late", "lefikhakh/ashrenu", 26, 26,
               [(26, 0, 1)]))
A.append(block("atah_hu_ad", "Thou wast the same before the world was created",
               "atah_hu/ad_shelo", 26, 26, [(26, 3, 0)]))
A.append(block("atah_hu_uvishuatkha", "May our strength rise", "atah_hu/uvishuatkha",
               26, 26, [(26, 3, 1)]))
A.append(block("atah_hu_bashamayim", "Thou, Lord our God, art in heaven",
               "atah_hu/bashamayim", 26, 26, [(26, 4)]))

# ---------------------------------------------------------------- en_korbanot
K = []
K.append(block("korbanot_kiyor", "The laver", "korbanot/kiyor", 28, 28, [(28, 0)]))
K.append(block("korbanot_yehi_ratzon_miqdash", "May it be thy will, to have mercy on us",
               "korbanot/yehi_ratzon_miqdash", 28, 28, [(28, 1)]))
K.append(block("korbanot_tamid", "The daily offering", "korbanot/tamid", 28, 30,
               [(28, 2), (30, 0)]))
K.append(block("korbanot_ushchat", "He shall slaughter it", "korbanot/ushchat", 30, 30,
               [(30, 1)]))
K.append(block("korbanot_yehi_ratzon_amirah", "May it be thy will, that this recital",
               "korbanot/yehi_ratzon_amirah", 30, 30, [(30, 2)]))
K.append(block("korbanot_atah_hu", "Thou art the Lord our God before whom",
               "korbanot/atah_hu", 30, 30, [(30, 3)]))
K.append(block("korbanot_ketoret", "The incense", "korbanot/ketoret", 30, 30, [(30, 4)]))
K.append(block("korbanot_pittum", "The compounding of the incense",
               "korbanot/pittum_haketoret", 30, 32, [(30, 5), (32, 0), (32, 1)],
               comment="#: One paragraph in Hebrew, three here."))
K.append(block("korbanot_rashbag", "Rabbi Simeon ben Gamaliel says",
               "korbanot/pittum_haketoret/rashbag", 32, 32, [(32, 2)]))
K.append(block("korbanot_rabbi_natan", "Rabbi Nathan says",
               "korbanot/pittum_haketoret/rabbi_natan", 32, 32, [(32, 3)]))
K.append(block("korbanot_bar_kappara", "Bar Kappara says",
               "korbanot/pittum_haketoret/bar_kappara", 32, 34, [(32, 4), (34, 0)]))
K.append(verse_block("korbanot_pesukim", "The Lord of hosts is with us",
                     "korbanot/pesukim", 34, 34, [(34, 1), (34, 2), (34, 3)],
                     comment="#: Centred lines on the Hebrew page, indented lines here."))
K.append(block("korbanot_atah_seter", "Thou art my shelter", "korbanot/atah_seter",
               34, 34, [(34, 4)]))
K.append(block("korbanot_vearvah", "The offering of Judah and Jerusalem",
               "korbanot/vearvah", 34, 34, [(34, 5)]))
K.append(block("korbanot_abaye", "Abbaye recounted the daily order",
               "korbanot/seder_hamaarakhah", 34, 34, [(34, 6)]))
K.append(verse_block("poem_ana_bekhoach", "By the great power", "ana_bekhoach", 34, 36,
                     [(34, 7), (34, 8), (36, 0), (36, 1), (36, 2), (36, 3), (36, 4)],
                     base=True,
                     comment="#: Seven lines, as the Hebrew has -- Birnbaum's footnote says\n"
                             "#: six words to each of seven lines and describes the Hebrew."))
K.append(block("korbanot_ribbon_haolamim", "Lord of the universe",
               "korbanot/ribbon_haolamim", 36, 36, [(36, 6)]))
K.append(block("korbanot_musaf_shabbat", "On the Sabbath day", "korbanot/musaf/shabbat",
               36, 36, [(36, 7)]))
K.append(block("korbanot_musaf_rosh_chodesh", "And on your new moon festivals",
               "korbanot/musaf/rosh_chodesh", 36, 38, [(36, 8), (38, 0)]))
for n, (page, index) in enumerate(
        [(38, 1), (38, 2), (38, 3), (40, 0), (40, 1), (40, 2), (40, 3)], start=1):
    K.append(block(f"eizehu_mekoman_{n}", f"Which were the places of sacrifice {n}",
                   f"eizehu_mekoman/{n}", page, page, [(page, index)]))
K.append(block("eizehu_mekoman_8", "Which were the places of sacrifice 8",
               "eizehu_mekoman/8", 40, 42, [(40, 4), (42, 0)]))

# ---------------------------------------------------------------- en_ishmael
I = []
I.append(block("ishmael_lead", "Rabbi Ishmael says", "middot/lead", 42, 42, [(42, 1)]))
RULES = [(42, i) for i in range(2, 8)] + [(44, i) for i in range(0, 6)] + [(46, 0)]
for n, (page, index) in enumerate(RULES, start=1):
    I.append(block(f"middot_{n}", f"Rule {n}", f"middot/{n}", page, page, [(page, index)]))
I.append(block("ishmael_yehi_ratzon", "May it be thy will, that the Temple be rebuilt",
               "middot/yehi_ratzon", 46, 46, [(46, 1)]))
for name, title, slug, page, index in [
    ("kaddish_derabbanan_yitgadal", "Glorified and sanctified",
     "kaddish/derabbanan/yitgadal", 46, 2),
    ("kaddish_derabbanan_yehe_shmeh", "May his great name be blessed",
     "kaddish/derabbanan/yehe_shmeh", 46, 3),
    ("kaddish_derabbanan_yitbarakh", "Blessed and praised",
     "kaddish/derabbanan/yitbarakh", 48, 0),
    ("kaddish_derabbanan_al_yisrael", "We pray for Israel",
     "kaddish/derabbanan/al_yisrael", 48, 1),
    ("kaddish_derabbanan_yehe_shlama", "May there be abundant peace",
     "kaddish/derabbanan/yehe_shlama", 48, 2),
    ("kaddish_derabbanan_oseh_shalom", "He who creates peace",
     "kaddish/derabbanan/oseh_shalom", 48, 3),
]:
    I.append(block(name, title, slug, page, page, [(page, index)]))

for module, doc, blocks in (("en_akedah", AKEDAH_DOC, A),
                            ("en_korbanot", KORBANOT_DOC, K),
                            ("en_ishmael", ISHMAEL_DOC, I)):
    out = pathlib.Path(f"opensiddur/importer/birnbaum_scan/build/{module}.py")
    out.write_text((HEAD % doc) + "\n" + "\n".join(blocks), encoding="utf-8")
    print("wrote", out, len(blocks), "prayers")
