annotations:
- birnbaum_ashkenaz_en_1949
declarations: {}
parallel:
  projects:
  - birnbaum_ashkenaz_en_1949
print_once:
  commentary: true
priority:
  transclusion:
  - birnbaum_ashkenaz_he_1949
  - birnbaum_ashkenaz_en_1949
typography:
  fonts:
    hebrew:
    - name: Frank Ruehl CLM
      normal_size: 12
    - name: Ezra SIL
      normal_size: 12
    - name: SBL Hebrew
      normal_size: 12
    - name: FreeSerif
      normal_size: 12
  instructions:
    from: both
